import os
import shutil
from fastapi import APIRouter, UploadFile, File, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.db.models import Document
from app.schemas.document import DocumentResponse
from app.services.embedding_service import update_vectorstore

router = APIRouter()

@router.post('/upload',response_model=DocumentResponse)
def upload_document(file:UploadFile=File(...),db:Session=Depends(get_db)):
    # Only allows pdf files 
    if not file.filename.endswith('pdf'):
        raise HTTPException(
            status_code=400,
            detail='...'
        )
    upload_dir='data/uploads'
    os.makedirs(upload_dir,exist_ok=True)
    file_path=os.path.join(upload_dir,file.filename)

    # Save file buffer
    with open(file_path,'wb') as buffer:
        shutil.copyfileobj(file.file,buffer)
    
    # Process PDF and update FAISS vectorstore!
    update_vectorstore(file_path)
    
    # DB record save
    pdf=Document(filename=file.filename,filepath=file_path)
    
    db.add(pdf)
    db.commit()
    # populates pdf.id and pdf.upload_date generated by DB
    db.refresh(pdf)         
    return pdf 